name: Meterian Scanner workflow

on: push

jobs:
    meterian_scan_autofix:
        name: Meterian scan
        runs-on: ubuntu-latest
        container:
            image: meterian/cli:2.3.66-gha
        steps: 
          - name: Checkout
            uses: actions/checkout@v3
          - name: Meterian Scanner
            run: | 
                VERSION="autofix-flags-update"
                if [[ -z "$VERSION" ]];then
                    VERSION=master
                fi

                curl -sS https://raw.githubusercontent.com/MeterianHQ/meterian-github-action/$VERSION/entrypoint.sh -o /root/entrypoint.sh
                curl -sS https://raw.githubusercontent.com/MeterianHQ/meterian-github-action/$VERSION/meterian.sh -o /root/meterian.sh

                currDir=$(pwd)
                THE_UID="$(stat -c '%u' "${currDir}")"
                THE_GID="$(stat -c '%g' "${currDir}")"
                chown -R $THE_UID:$THE_GID .

                /root/entrypoint.sh 
            env:
              METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
              GITHUB_TOKEN: ${{ github.token }}
              ALWAYS_OPEN_PRS: true
              INPUT_AUTOFIX_SECURITY: safe
              INPUT_AUTOFIX_WITH_PR: true
              INPUT_AUTOFIX_WITH_REPORT: true
              INPUT_CLI_ARGS: --debug
# 2.3.66
