name: Meterian Scanner workflow

on: push

jobs:
    meterian_scan_autofix:
        name: Meterian scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v3
          - name: Meterian Scanner
            uses: MeterianHQ/meterian-github-action@v1.0.15
            env:
              METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
#               GITHUB_TOKEN: ${{ github.token }}
              GITHUB_TOKEN: ${{ secrets.GH_PAT }}
              ALWAYS_OPEN_PRS: true
            with:
              # autofix_security: safe
              # autofix_with_pr: true
              # autofix_with_report: true
              cli_args: --scopes=prod --report-console:stability
              
