name: Meterian Scanner workflow

on: push

jobs:
    meterian_scan_autofix:
        name: Meterian scan
        runs-on: ubuntu-latest
        container:
            image: meterian/cli:2.3.66-gha
        steps: 
          - name: Checkout
            uses: actions/checkout@v3
          - name: Meterian Scanner
            run: meterian_github_action.sh autofix-flags-update
            env:
              METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
              GITHUB_TOKEN: ${{ github.token }}
              ALWAYS_OPEN_PRS: true
              INPUT_AUTOFIX_SECURITY: safe
              INPUT_AUTOFIX_WITH_PR: true
              INPUT_AUTOFIX_WITH_REPORT: true
              INPUT_CLI_ARGS: --debug
# 2.3.66
