name: Meterian Scanner workflow

on: push

jobs:
    meterian_scan_autofix:
        name: Meterian scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v3
          - name: Meterian Scanner
            uses: MeterianHQ/meterian-github-action@autofix-flags-update
            env:
              METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
              GITHUB_TOKEN: ${{ github.token }}
            with:
              autofix_stability: conservative
              autofix_with_issue: true
              autofix_with_report: true
